### PR TITLE
Add joins

### PR DESCRIPTION
**Pull request by patrickofriel-wk**
Adding parsing for right and full joins. (Also contains pull requests #10 and #11)

### CODE REVIEW

**Comment by mbaumgartl** [comment]
We don't like merge commits in our history. After you removed that kind of commit from your pull request, we are happy to add the new feature to the parser!

Thanks for contributing!

**Comment by patrickofriel-wk** [comment]
Sure! Do y'all have a command or process that you generally use to rebase without those merge commits that I can copy?

**Comment by not-implemented** [comment]
There are a lot of ways to do this - you need both remotes in one repo - here a complete example:

```bash
# clone original repo (with default name "origin"):
git clone https://github.com/godmodelabs/flora-sql-parser.git
cd flora-sql-parser

# add forked repo as remote (with name "patrickofriel-wk"):
git remote add patrickofriel-wk https://github.com/patrickofriel-wk/flora-sql-parser.git
git fetch patrickofriel-wk

# checkout the branch which should be rebased (in this case your "master" branch from the
# pull request - but we name it "feature-branch" locally to avoid name clashes - you see
# it is a little bit easier to work with feature-branches in pull-requests ;-)):
git checkout -b feature-branch patrickofriel-wk/master

# time to rebase - in this case we have to drop your first commit "update alias
# to use double instead of single quotes (#1)", because it is already in origin/master
# and would just produce a conflict - so we do an interactive rebase (onto
# our "official" master):
git rebase -i origin/master

# change the first commit from "pick" to "drop" - save and close the editor

# (of course if there are no conflicts you can just do a normal
# non-interactive "git rebase origin/master")

# as we have rewritten the history now, we have to force-push the
# feature-branch (back to "master"):
git push --force-with-lease patrickofriel-wk feature-branch:master

# done - should be visible in the pull-request immediately
```

By the way: I saw, you already created some feature-branches - just a hint for the future: If the features are logically independent, you should always checkout the "master" before you start the next feature - then they are really independent and you can create inividual pull-requests for them (because all commits are based on master then). But don't worry for this time :-)

Greets and thanks for contributing!

**Comment by patrickofriel-wk** [comment]
Completely understand, the problem was we were consuming the master of my fork so we could get the latest changes so I was merging each feature branch first into our forked master and then creating new branches off of that. We probably should've created a specific branch on the fork for consumption instead of merging into our forked master.

I went ahead and made specific feature branches for each pull request and opened a new one for each with clean commits.

Closing this one in favor of #16

**Comment by not-implemented** [comment]
Perfect, thanks! We will have a look at the pull-requests next week.

**Pull request closed without merging**
